Repository spacetelescope/stsci.stimage, pull requests merged in 2025-03, with the labels that each got.

#55 TST: Fix CI and devdeps workflow logic
  .github/workflows/ci.yml
  .github/workflows/test_devdeps.yml
Labels: run devdeps tests

#58 Use local xorder instead of s->xorder
  .github/workflows/ci.yml
  .github/workflows/test_devdeps.yml
  src/surface/fit.c
  test_c/test_c.py
Labels: bug

#59 Replace WAF with CMake
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/test_devdeps.yml
  .gitignore
  CMakeLists.txt
  get_waf.py
  src/CMakeLists.txt
  src/wscript
  test_c/CMakeLists.txt
  test_c/disabled_test_c.py
  test_c/test.h
  test_c/test_xyxymatch_triangles.c
  test_c/wscript
  tox.ini
  wscript
Labels: Maintenance
